import { Task } from '../../app/model/task.model';

export const DUMMY_TASKS: Task[] = [
  // User 1 - Alice Johnson (3 tasks)
  {
    id: 1,
    userId: 1,
    work: 'Complete project documentation',
    priority: 'High',
    title: 'Project Documentation',
    description: 'Update the API documentation with new endpoints and examples',
    dueDate: 'Dec 15, 2024',
    estimatedHours: 2,
    isCompleted: true,
  },
  {
    id: 2,
    userId: 1,
    work: 'Frontend UI implementation',
    priority: 'High',
    title: 'User Dashboard',
    description: 'Implement the main user dashboard with responsive design',
    dueDate: 'Dec 20, 2024',
    estimatedHours: 4,
    isCompleted: false,
  },
  {
    id: 3,
    userId: 1,
    work: 'Code review and refactoring',
    priority: 'Medium',
    title: 'Code Quality',
    description: 'Review and refactor existing code for better maintainability',
    dueDate: 'Dec 19, 2024',
    estimatedHours: 3,
    isCompleted: true,
  },

  // User 2 - Bob Smith (4 tasks)
  {
    id: 4,
    userId: 2,
    work: 'Backend API development',
    priority: 'Medium',
    title: 'Authentication System',
    description: 'Build JWT-based authentication with user roles',
    dueDate: 'Dec 18, 2024',
    estimatedHours: 6,
    isCompleted: true,
  },
  {
    id: 5,
    userId: 2,
    work: 'Database schema design',
    priority: 'Medium',
    title: 'Database Architecture',
    description: 'Design and implement the database schema for the application',
    dueDate: 'Dec 16, 2024',
    estimatedHours: 3,
    isCompleted: false,
  },
  {
    id: 6,
    userId: 2,
    work: 'Performance optimization',
    priority: 'Low',
    title: 'Performance Tuning',
    description: 'Optimize application performance and loading times',
    dueDate: 'Dec 23, 2024',
    estimatedHours: 4,
    isCompleted: false,
  },
  {
    id: 7,
    userId: 2,
    work: 'Security audit',
    priority: 'High',
    title: 'Security Review',
    description: 'Conduct comprehensive security audit of the application',
    dueDate: 'Dec 21, 2024',
    estimatedHours: 5,
    isCompleted: true,
  },

  // User 3 - Charlie Brown (3 tasks)
  {
    id: 8,
    userId: 3,
    work: 'Testing and quality assurance',
    priority: 'Low',
    title: 'Unit Tests',
    description: 'Write comprehensive unit tests for all components',
    dueDate: 'Dec 22, 2024',
    estimatedHours: 5,
    isCompleted: true,
  },
  {
    id: 9,
    userId: 3,
    work: 'Integration testing',
    priority: 'Medium',
    title: 'API Integration Tests',
    description: 'Create end-to-end integration tests for all APIs',
    dueDate: 'Dec 17, 2024',
    estimatedHours: 4,
    isCompleted: false,
  },
  {
    id: 10,
    userId: 3,
    work: 'User acceptance testing',
    priority: 'High',
    title: 'UAT Planning',
    description: 'Plan and coordinate user acceptance testing sessions',
    dueDate: 'Dec 24, 2024',
    estimatedHours: 3,
    isCompleted: false,
  },

  // User 4 - David Miller (4 tasks)
  {
    id: 11,
    userId: 4,
    work: 'Deployment preparation',
    priority: 'High',
    title: 'Production Deployment',
    description: 'Prepare the application for production deployment',
    dueDate: 'Dec 25, 2024',
    estimatedHours: 2,
    isCompleted: true,
  },
  {
    id: 12,
    userId: 4,
    work: 'CI/CD pipeline setup',
    priority: 'Medium',
    title: 'DevOps Pipeline',
    description: 'Set up continuous integration and deployment pipeline',
    dueDate: 'Dec 26, 2024',
    estimatedHours: 6,
    isCompleted: false,
  },
  {
    id: 13,
    userId: 4,
    work: 'Monitoring and logging',
    priority: 'Low',
    title: 'System Monitoring',
    description: 'Implement application monitoring and logging systems',
    dueDate: 'Dec 28, 2024',
    estimatedHours: 4,
    isCompleted: true,
  },
  {
    id: 14,
    userId: 4,
    work: 'Infrastructure setup',
    priority: 'Medium',
    title: 'Cloud Infrastructure',
    description: 'Set up cloud infrastructure and deployment environments',
    dueDate: 'Dec 29, 2024',
    estimatedHours: 5,
    isCompleted: false,
  },

  // User 5 - Eva Williams (4 tasks)
  {
    id: 15,
    userId: 5,
    work: 'UI/UX design review',
    priority: 'Medium',
    title: 'Design Review',
    description: 'Review and approve final UI/UX designs',
    dueDate: 'Dec 27, 2024',
    estimatedHours: 2,
    isCompleted: true,
  },
  {
    id: 16,
    userId: 5,
    work: 'Accessibility compliance',
    priority: 'High',
    title: 'Accessibility Audit',
    description: 'Ensure application meets WCAG accessibility standards',
    dueDate: 'Dec 29, 2024',
    estimatedHours: 3,
    isCompleted: false,
  },
  {
    id: 17,
    userId: 5,
    work: 'Cross-browser testing',
    priority: 'Low',
    title: 'Browser Compatibility',
    description: 'Test application across different browsers and devices',
    dueDate: 'Dec 30, 2024',
    estimatedHours: 4,
    isCompleted: true,
  },
  {
    id: 18,
    userId: 5,
    work: 'Mobile responsiveness',
    priority: 'Medium',
    title: 'Mobile Optimization',
    description: 'Optimize application for mobile devices',
    dueDate: 'Dec 31, 2024',
    estimatedHours: 3,
    isCompleted: false,
  },

  // User 6 - Frank Harris (3 tasks)
  {
    id: 19,
    userId: 6,
    work: 'Documentation review',
    priority: 'Low',
    title: 'Docs Review',
    description: 'Review and update all project documentation',
    dueDate: 'Jan 2, 2025',
    estimatedHours: 2,
    isCompleted: true,
  },
  {
    id: 20,
    userId: 6,
    work: 'Training material creation',
    priority: 'Medium',
    title: 'Training Docs',
    description: 'Create training materials for end users',
    dueDate: 'Jan 3, 2025',
    estimatedHours: 5,
    isCompleted: false,
  },
  {
    id: 21,
    userId: 6,
    work: 'Knowledge base setup',
    priority: 'Low',
    title: 'Knowledge Base',
    description: 'Set up internal knowledge base for the team',
    dueDate: 'Jan 5, 2025',
    estimatedHours: 3,
    isCompleted: true,
  },

  // User 7 - Grace Lee (4 tasks)
  {
    id: 22,
    userId: 7,
    work: 'Code optimization',
    priority: 'Medium',
    title: 'Performance Review',
    description: 'Review and optimize critical code paths',
    dueDate: 'Jan 6, 2025',
    estimatedHours: 4,
    isCompleted: false,
  },
  {
    id: 23,
    userId: 7,
    work: 'Memory leak detection',
    priority: 'High',
    title: 'Memory Management',
    description: 'Identify and fix memory leaks in the application',
    dueDate: 'Jan 7, 2025',
    estimatedHours: 3,
    isCompleted: true,
  },
  {
    id: 24,
    userId: 7,
    work: 'Error handling improvement',
    priority: 'Medium',
    title: 'Error Handling',
    description: 'Improve error handling and user feedback',
    dueDate: 'Jan 8, 2025',
    estimatedHours: 2,
    isCompleted: false,
  },
  {
    id: 25,
    userId: 7,
    work: 'Code profiling',
    priority: 'Low',
    title: 'Performance Profiling',
    description: 'Profile application code for performance bottlenecks',
    dueDate: 'Jan 9, 2025',
    estimatedHours: 4,
    isCompleted: true,
  },

  // User 8 - Henry Clark (3 tasks)
  {
    id: 26,
    userId: 8,
    work: 'Database optimization',
    priority: 'High',
    title: 'DB Performance',
    description: 'Optimize database queries and indexes',
    dueDate: 'Jan 10, 2025',
    estimatedHours: 5,
    isCompleted: false,
  },
  {
    id: 27,
    userId: 8,
    work: 'Backup strategy',
    priority: 'Medium',
    title: 'Data Backup',
    description: 'Implement automated backup and recovery strategy',
    dueDate: 'Jan 11, 2025',
    estimatedHours: 3,
    isCompleted: true,
  },
  {
    id: 28,
    userId: 8,
    work: 'Data migration planning',
    priority: 'Low',
    title: 'Migration Plan',
    description: 'Plan data migration strategy for production',
    dueDate: 'Jan 12, 2025',
    estimatedHours: 4,
    isCompleted: false,
  },

  // User 9 - Ivy Lewis (4 tasks)
  {
    id: 29,
    userId: 9,
    work: 'API rate limiting',
    priority: 'Medium',
    title: 'Rate Limiting',
    description: 'Implement API rate limiting and throttling',
    dueDate: 'Jan 13, 2025',
    estimatedHours: 3,
    isCompleted: true,
  },
  {
    id: 30,
    userId: 9,
    work: 'API versioning',
    priority: 'Low',
    title: 'API Versioning',
    description: 'Implement API versioning strategy',
    dueDate: 'Jan 14, 2025',
    estimatedHours: 2,
    isCompleted: false,
  },
  {
    id: 31,
    userId: 9,
    work: 'API documentation update',
    priority: 'Medium',
    title: 'API Docs',
    description: 'Update API documentation with latest changes',
    dueDate: 'Jan 15, 2025',
    estimatedHours: 4,
    isCompleted: true,
  },
  {
    id: 32,
    userId: 9,
    work: 'API testing automation',
    priority: 'High',
    title: 'API Test Automation',
    description: 'Automate API testing processes',
    dueDate: 'Jan 16, 2025',
    estimatedHours: 5,
    isCompleted: false,
  },

  // User 10 - Jack Walker (3 tasks)
  {
    id: 33,
    userId: 10,
    work: 'Final testing',
    priority: 'High',
    title: 'Final QA',
    description: 'Conduct final quality assurance testing',
    dueDate: 'Jan 17, 2025',
    estimatedHours: 6,
    isCompleted: false,
  },
  {
    id: 34,
    userId: 10,
    work: 'Bug fixes',
    priority: 'High',
    title: 'Critical Fixes',
    description: 'Fix any critical bugs found during testing',
    dueDate: 'Jan 18, 2025',
    estimatedHours: 3,
    isCompleted: true,
  },
  {
    id: 35,
    userId: 10,
    work: 'Release notes',
    priority: 'Medium',
    title: 'Release Documentation',
    description: 'Prepare release notes and changelog',
    dueDate: 'Jan 19, 2025',
    estimatedHours: 2,
    isCompleted: false,
  },

  // User 11 - Kara Young (4 tasks)
  {
    id: 36,
    userId: 11,
    work: 'Frontend testing',
    priority: 'Medium',
    title: 'Frontend QA',
    description: 'Test all frontend components and interactions',
    dueDate: 'Jan 20, 2025',
    estimatedHours: 4,
    isCompleted: false,
  },
  {
    id: 37,
    userId: 11,
    work: 'User interface validation',
    priority: 'Low',
    title: 'UI Validation',
    description: 'Validate user interface against design specifications',
    dueDate: 'Jan 21, 2025',
    estimatedHours: 3,
    isCompleted: false,
  },
  {
    id: 38,
    userId: 11,
    work: 'Responsive design testing',
    priority: 'Medium',
    title: 'Responsive Testing',
    description: 'Test responsive design across different screen sizes',
    dueDate: 'Jan 22, 2025',
    estimatedHours: 2,
    isCompleted: false,
  },
  {
    id: 39,
    userId: 11,
    work: 'Accessibility testing',
    priority: 'High',
    title: 'A11y Testing',
    description: 'Test application accessibility features',
    dueDate: 'Jan 23, 2025',
    estimatedHours: 4,
    isCompleted: false,
  },

  // User 12 - Liam Scott (3 tasks)
  {
    id: 40,
    userId: 12,
    work: 'Backend testing',
    priority: 'Medium',
    title: 'Backend QA',
    description: 'Test all backend services and APIs',
    dueDate: 'Jan 24, 2025',
    estimatedHours: 5,
    isCompleted: false,
  },
  {
    id: 41,
    userId: 12,
    work: 'Database testing',
    priority: 'Low',
    title: 'Database QA',
    description: 'Test database operations and data integrity',
    dueDate: 'Jan 25, 2025',
    estimatedHours: 3,
    isCompleted: false,
  },
  {
    id: 42,
    userId: 12,
    work: 'Performance testing',
    priority: 'High',
    title: 'Performance QA',
    description: 'Conduct performance and load testing',
    dueDate: 'Jan 26, 2025',
    estimatedHours: 6,
    isCompleted: false,
  },

  // User 13 - Mia Adams (4 tasks)
  {
    id: 43,
    userId: 13,
    work: 'Security testing',
    priority: 'High',
    title: 'Security QA',
    description: 'Conduct security testing and vulnerability assessment',
    dueDate: 'Jan 27, 2025',
    estimatedHours: 5,
    isCompleted: false,
  },
  {
    id: 44,
    userId: 13,
    work: 'Penetration testing',
    priority: 'Medium',
    title: 'Pen Testing',
    description: 'Perform penetration testing on the application',
    dueDate: 'Jan 28, 2025',
    estimatedHours: 4,
    isCompleted: false,
  },
  {
    id: 45,
    userId: 13,
    work: 'Code security review',
    priority: 'Low',
    title: 'Security Code Review',
    description: 'Review code for security vulnerabilities',
    dueDate: 'Jan 29, 2025',
    estimatedHours: 3,
    isCompleted: false,
  },
  {
    id: 46,
    userId: 13,
    work: 'Security documentation',
    priority: 'Medium',
    title: 'Security Docs',
    description: 'Document security policies and procedures',
    dueDate: 'Jan 30, 2025',
    estimatedHours: 2,
    isCompleted: false,
  },

  // User 14 - Noah Hill (3 tasks)
  {
    id: 47,
    userId: 14,
    work: 'DevOps automation',
    priority: 'Medium',
    title: 'DevOps Automation',
    description: 'Automate deployment and infrastructure processes',
    dueDate: 'Jan 31, 2025',
    estimatedHours: 6,
    isCompleted: false,
  },
  {
    id: 48,
    userId: 14,
    work: 'Container orchestration',
    priority: 'High',
    title: 'Container Management',
    description: 'Set up and manage container orchestration',
    dueDate: 'Feb 1, 2025',
    estimatedHours: 4,
    isCompleted: false,
  },
  {
    id: 49,
    userId: 14,
    work: 'Infrastructure monitoring',
    priority: 'Low',
    title: 'Infra Monitoring',
    description: 'Implement infrastructure monitoring and alerting',
    dueDate: 'Feb 2, 2025',
    estimatedHours: 3,
    isCompleted: false,
  },

  // User 15 - Olivia King (4 tasks)
  {
    id: 50,
    userId: 15,
    work: 'User experience design',
    priority: 'Medium',
    title: 'UX Design',
    description: 'Design user experience flows and interactions',
    dueDate: 'Feb 3, 2025',
    estimatedHours: 5,
    isCompleted: false,
  },
  {
    id: 51,
    userId: 15,
    work: 'User research',
    priority: 'Low',
    title: 'User Research',
    description: 'Conduct user research and usability studies',
    dueDate: 'Feb 4, 2025',
    estimatedHours: 4,
    isCompleted: false,
  },
  {
    id: 52,
    userId: 15,
    work: 'Prototype development',
    priority: 'High',
    title: 'Prototyping',
    description: 'Develop interactive prototypes for user testing',
    dueDate: 'Feb 5, 2025',
    estimatedHours: 6,
    isCompleted: false,
  },
  {
    id: 53,
    userId: 15,
    work: 'Design system creation',
    priority: 'Medium',
    title: 'Design System',
    description: 'Create and maintain design system components',
    dueDate: 'Feb 6, 2025',
    estimatedHours: 3,
    isCompleted: false,
  },

  // User 16 - Paul Wright (3 tasks)
  {
    id: 54,
    userId: 16,
    work: 'Data analytics implementation',
    priority: 'Medium',
    title: 'Analytics',
    description: 'Implement data analytics and reporting features',
    dueDate: 'Feb 7, 2025',
    estimatedHours: 5,
    isCompleted: false,
  },
  {
    id: 55,
    userId: 16,
    work: 'Business intelligence',
    priority: 'Low',
    title: 'BI Dashboard',
    description: 'Create business intelligence dashboard',
    dueDate: 'Feb 8, 2025',
    estimatedHours: 4,
    isCompleted: false,
  },
  {
    id: 56,
    userId: 16,
    work: 'Data visualization',
    priority: 'High',
    title: 'Data Viz',
    description: 'Implement data visualization components',
    dueDate: 'Feb 9, 2025',
    estimatedHours: 3,
    isCompleted: false,
  },

  // User 17 - Quinn Green (4 tasks)
  {
    id: 57,
    userId: 17,
    work: 'Machine learning integration',
    priority: 'High',
    title: 'ML Integration',
    description: 'Integrate machine learning models into the application',
    dueDate: 'Feb 10, 2025',
    estimatedHours: 8,
    isCompleted: false,
  },
  {
    id: 58,
    userId: 17,
    work: 'AI feature development',
    priority: 'Medium',
    title: 'AI Features',
    description: 'Develop AI-powered features and recommendations',
    dueDate: 'Feb 11, 2025',
    estimatedHours: 6,
    isCompleted: false,
  },
  {
    id: 59,
    userId: 17,
    work: 'Data preprocessing',
    priority: 'Low',
    title: 'Data Prep',
    description: 'Implement data preprocessing pipelines',
    dueDate: 'Feb 12, 2025',
    estimatedHours: 4,
    isCompleted: false,
  },
  {
    id: 60,
    userId: 17,
    work: 'Model validation',
    priority: 'Medium',
    title: 'Model Validation',
    description: 'Validate machine learning model performance',
    dueDate: 'Feb 13, 2025',
    estimatedHours: 3,
    isCompleted: false,
  },

  // User 18 - Ryan Hall (3 tasks)
  {
    id: 61,
    userId: 18,
    work: 'Mobile app development',
    priority: 'High',
    title: 'Mobile App',
    description: 'Develop native mobile application',
    dueDate: 'Feb 14, 2025',
    estimatedHours: 10,
    isCompleted: false,
  },
  {
    id: 62,
    userId: 18,
    work: 'Mobile testing',
    priority: 'Medium',
    title: 'Mobile Testing',
    description: 'Test mobile application on various devices',
    dueDate: 'Feb 15, 2025',
    estimatedHours: 4,
    isCompleted: false,
  },
  {
    id: 63,
    userId: 18,
    work: 'App store deployment',
    priority: 'Low',
    title: 'App Store',
    description: 'Prepare and deploy to app stores',
    dueDate: 'Feb 16, 2025',
    estimatedHours: 2,
    isCompleted: false,
  },

  // User 19 - Sophia Allen (4 tasks)
  {
    id: 64,
    userId: 19,
    work: 'Cloud migration',
    priority: 'High',
    title: 'Cloud Migration',
    description: 'Migrate application to cloud infrastructure',
    dueDate: 'Feb 17, 2025',
    estimatedHours: 8,
    isCompleted: false,
  },
  {
    id: 65,
    userId: 19,
    work: 'Multi-region deployment',
    priority: 'Medium',
    title: 'Multi-Region',
    description: 'Deploy application across multiple regions',
    dueDate: 'Feb 18, 2025',
    estimatedHours: 5,
    isCompleted: false,
  },
  {
    id: 66,
    userId: 19,
    work: 'Load balancing setup',
    priority: 'Low',
    title: 'Load Balancing',
    description: 'Set up load balancing for high availability',
    dueDate: 'Feb 19, 2025',
    estimatedHours: 3,
    isCompleted: false,
  },
  {
    id: 67,
    userId: 19,
    work: 'Auto-scaling configuration',
    priority: 'Medium',
    title: 'Auto-Scaling',
    description: 'Configure auto-scaling policies',
    dueDate: 'Feb 20, 2025',
    estimatedHours: 4,
    isCompleted: false,
  },

  // User 20 - Thomas Perez (3 tasks)
  {
    id: 68,
    userId: 20,
    work: 'Compliance audit',
    priority: 'High',
    title: 'Compliance',
    description: 'Conduct compliance audit for industry standards',
    dueDate: 'Feb 21, 2025',
    estimatedHours: 6,
    isCompleted: false,
  },
  {
    id: 69,
    userId: 20,
    work: 'Regulatory documentation',
    priority: 'Medium',
    title: 'Regulatory Docs',
    description: 'Prepare regulatory compliance documentation',
    dueDate: 'Feb 22, 2025',
    estimatedHours: 4,
    isCompleted: false,
  },
  {
    id: 70,
    userId: 20,
    work: 'Audit trail implementation',
    priority: 'Low',
    title: 'Audit Trail',
    description: 'Implement comprehensive audit trail system',
    dueDate: 'Feb 23, 2025',
    estimatedHours: 3,
    isCompleted: false,
  },

  // User 21 - Uma Rivera (4 tasks)
  {
    id: 71,
    userId: 21,
    work: 'Internationalization',
    priority: 'Medium',
    title: 'i18n',
    description: 'Implement internationalization and localization',
    dueDate: 'Feb 24, 2025',
    estimatedHours: 5,
    isCompleted: false,
  },
  {
    id: 72,
    userId: 21,
    work: 'Multi-language support',
    priority: 'High',
    title: 'Multi-Language',
    description: 'Add support for multiple languages',
    dueDate: 'Feb 25, 2025',
    estimatedHours: 6,
    isCompleted: false,
  },
  {
    id: 73,
    userId: 21,
    work: 'Cultural adaptation',
    priority: 'Low',
    title: 'Cultural Adaptation',
    description: 'Adapt application for different cultural contexts',
    dueDate: 'Feb 26, 2025',
    estimatedHours: 3,
    isCompleted: false,
  },
  {
    id: 74,
    userId: 21,
    work: 'Translation management',
    priority: 'Medium',
    title: 'Translation',
    description: 'Set up translation management system',
    dueDate: 'Feb 27, 2025',
    estimatedHours: 4,
    isCompleted: false,
  },

  // User 22 - Victor Brooks (3 tasks)
  {
    id: 75,
    userId: 22,
    work: 'API gateway implementation',
    priority: 'High',
    title: 'API Gateway',
    description: 'Implement API gateway for microservices',
    dueDate: 'Feb 28, 2025',
    estimatedHours: 7,
    isCompleted: false,
  },
  {
    id: 76,
    userId: 22,
    work: 'Service mesh setup',
    priority: 'Medium',
    title: 'Service Mesh',
    description: 'Set up service mesh for microservices communication',
    dueDate: 'Mar 1, 2025',
    estimatedHours: 5,
    isCompleted: false,
  },
  {
    id: 77,
    userId: 22,
    work: 'Microservices architecture',
    priority: 'Low',
    title: 'Microservices',
    description: 'Design and implement microservices architecture',
    dueDate: 'Mar 2, 2025',
    estimatedHours: 8,
    isCompleted: false,
  },

  // User 23 - Wendy Foster (4 tasks)
  {
    id: 78,
    userId: 23,
    work: 'Real-time features',
    priority: 'High',
    title: 'Real-Time',
    description: 'Implement real-time features and WebSocket support',
    dueDate: 'Mar 3, 2025',
    estimatedHours: 6,
    isCompleted: false,
  },
  {
    id: 79,
    userId: 23,
    work: 'Push notifications',
    priority: 'Medium',
    title: 'Push Notifications',
    description: 'Implement push notification system',
    dueDate: 'Mar 4, 2025',
    estimatedHours: 4,
    isCompleted: false,
  },
  {
    id: 80,
    userId: 23,
    work: 'Live chat integration',
    priority: 'Low',
    title: 'Live Chat',
    description: 'Integrate live chat functionality',
    dueDate: 'Mar 5, 2025',
    estimatedHours: 3,
    isCompleted: false,
  },
  {
    id: 81,
    userId: 23,
    work: 'Real-time analytics',
    priority: 'Medium',
    title: 'Real-Time Analytics',
    description: 'Implement real-time analytics dashboard',
    dueDate: 'Mar 6, 2025',
    estimatedHours: 5,
    isCompleted: false,
  },

  // User 24 - Xavier Simmons (3 tasks)
  {
    id: 82,
    userId: 24,
    work: 'Blockchain integration',
    priority: 'High',
    title: 'Blockchain',
    description: 'Integrate blockchain technology for secure transactions',
    dueDate: 'Mar 7, 2025',
    estimatedHours: 10,
    isCompleted: false,
  },
  {
    id: 83,
    userId: 24,
    work: 'Smart contract development',
    priority: 'Medium',
    title: 'Smart Contracts',
    description: 'Develop smart contracts for business logic',
    dueDate: 'Mar 8, 2025',
    estimatedHours: 6,
    isCompleted: false,
  },
  {
    id: 84,
    userId: 24,
    work: 'Cryptocurrency payment',
    priority: 'Low',
    title: 'Crypto Payments',
    description: 'Implement cryptocurrency payment processing',
    dueDate: 'Mar 9, 2025',
    estimatedHours: 4,
    isCompleted: false,
  },

  // User 25 - Yara Torres (4 tasks)
  {
    id: 85,
    userId: 25,
    work: 'Virtual reality features',
    priority: 'Medium',
    title: 'VR Features',
    description: 'Implement virtual reality features and experiences',
    dueDate: 'Mar 10, 2025',
    estimatedHours: 8,
    isCompleted: false,
  },
  {
    id: 86,
    userId: 25,
    work: 'Augmented reality',
    priority: 'High',
    title: 'AR Features',
    description: 'Develop augmented reality capabilities',
    dueDate: 'Mar 11, 2025',
    estimatedHours: 7,
    isCompleted: false,
  },
  {
    id: 87,
    userId: 25,
    work: '3D modeling integration',
    priority: 'Low',
    title: '3D Modeling',
    description: 'Integrate 3D modeling and visualization',
    dueDate: 'Mar 12, 2025',
    estimatedHours: 5,
    isCompleted: false,
  },
  {
    id: 88,
    userId: 25,
    work: 'Immersive experiences',
    priority: 'Medium',
    title: 'Immersive UX',
    description: 'Create immersive user experiences',
    dueDate: 'Mar 13, 2025',
    estimatedHours: 4,
    isCompleted: false,
  },

  // User 26 - Zack Ramirez (3 tasks)
  {
    id: 89,
    userId: 26,
    work: 'IoT device integration',
    priority: 'High',
    title: 'IoT Integration',
    description: 'Integrate Internet of Things devices',
    dueDate: 'Mar 14, 2025',
    estimatedHours: 6,
    isCompleted: false,
  },
  {
    id: 90,
    userId: 26,
    work: 'Sensor data processing',
    priority: 'Medium',
    title: 'Sensor Data',
    description: 'Process and analyze sensor data from IoT devices',
    dueDate: 'Mar 15, 2025',
    estimatedHours: 4,
    isCompleted: false,
  },
  {
    id: 91,
    userId: 26,
    work: 'Device management',
    priority: 'Low',
    title: 'Device Management',
    description: 'Implement IoT device management system',
    dueDate: 'Mar 16, 2025',
    estimatedHours: 3,
    isCompleted: false,
  },

  // User 27 - Amelia Sanders (4 tasks)
  {
    id: 92,
    userId: 27,
    work: 'Data warehouse setup',
    priority: 'Medium',
    title: 'Data Warehouse',
    description: 'Set up data warehouse for analytics',
    dueDate: 'Mar 17, 2025',
    estimatedHours: 8,
    isCompleted: false,
  },
  {
    id: 93,
    userId: 27,
    work: 'ETL pipeline development',
    priority: 'High',
    title: 'ETL Pipeline',
    description: 'Develop ETL pipelines for data processing',
    dueDate: 'Mar 18, 2025',
    estimatedHours: 6,
    isCompleted: false,
  },
  {
    id: 94,
    userId: 27,
    work: 'Data governance',
    priority: 'Low',
    title: 'Data Governance',
    description: 'Implement data governance policies',
    dueDate: 'Mar 19, 2025',
    estimatedHours: 4,
    isCompleted: false,
  },
  {
    id: 95,
    userId: 27,
    work: 'Data quality monitoring',
    priority: 'Medium',
    title: 'Data Quality',
    description: 'Set up data quality monitoring and alerts',
    dueDate: 'Mar 20, 2025',
    estimatedHours: 3,
    isCompleted: false,
  },

  // User 28 - Benjamin Morris (3 tasks)
  {
    id: 96,
    userId: 28,
    work: 'Disaster recovery planning',
    priority: 'High',
    title: 'Disaster Recovery',
    description: 'Plan and implement disaster recovery procedures',
    dueDate: 'Mar 21, 2025',
    estimatedHours: 5,
    isCompleted: false,
  },
  {
    id: 97,
    userId: 28,
    work: 'Business continuity',
    priority: 'Medium',
    title: 'Business Continuity',
    description: 'Ensure business continuity during disruptions',
    dueDate: 'Mar 22, 2025',
    estimatedHours: 4,
    isCompleted: false,
  },
  {
    id: 98,
    userId: 28,
    work: 'Backup verification',
    priority: 'Low',
    title: 'Backup Verification',
    description: 'Verify backup and recovery procedures',
    dueDate: 'Mar 23, 2025',
    estimatedHours: 2,
    isCompleted: false,
  },

  // User 29 - Chloe Rogers (4 tasks)
  {
    id: 99,
    userId: 29,
    work: 'Performance optimization',
    priority: 'High',
    title: 'Performance Optimization',
    description: 'Optimize application performance and scalability',
    dueDate: 'Mar 24, 2025',
    estimatedHours: 6,
    isCompleted: false,
  },
  {
    id: 100,
    userId: 29,
    work: 'Load testing',
    priority: 'Medium',
    title: 'Load Testing',
    description: 'Conduct comprehensive load testing',
    dueDate: 'Mar 25, 2025',
    estimatedHours: 4,
    isCompleted: false,
  },
  {
    id: 101,
    userId: 29,
    work: 'Stress testing',
    priority: 'Low',
    title: 'Stress Testing',
    description: 'Perform stress testing under extreme conditions',
    dueDate: 'Mar 26, 2025',
    estimatedHours: 3,
    isCompleted: false,
  },
  {
    id: 102,
    userId: 29,
    work: 'Capacity planning',
    priority: 'Medium',
    title: 'Capacity Planning',
    description: 'Plan system capacity for future growth',
    dueDate: 'Mar 27, 2025',
    estimatedHours: 5,
    isCompleted: false,
  },

  // User 30 - Daniel Reed (3 tasks)
  {
    id: 103,
    userId: 30,
    work: 'Final deployment',
    priority: 'High',
    title: 'Final Deployment',
    description: 'Execute final production deployment',
    dueDate: 'Mar 28, 2025',
    estimatedHours: 3,
    isCompleted: false,
  },
  {
    id: 104,
    userId: 30,
    work: 'Go-live support',
    priority: 'Medium',
    title: 'Go-Live Support',
    description: 'Provide support during application go-live',
    dueDate: 'Mar 29, 2025',
    estimatedHours: 4,
    isCompleted: false,
  },
  {
    id: 105,
    userId: 30,
    work: 'Post-launch monitoring',
    priority: 'Low',
    title: 'Post-Launch',
    description: 'Monitor application performance post-launch',
    dueDate: 'Mar 30, 2025',
    estimatedHours: 2,
    isCompleted: false,
  },
];
